build:
  image: coreboot/coreboot-sdk:1.52
  tags:
   - local
  script:
    - cp configs/config.clevo_nv41mz .config
    - make olddefconfig
    - make -j $(nproc)
  artifacts:
    name: coreboot
    paths:
      - build/coreboot.rom
