services:
  - docker:dind

variables:
  RELEASE_DIR: ${CI_PROJECT_DIR}

stages:
  - check_dependiences
  - build_heads
  - build_coreboot

check_dependiences:
  stage: check_dependiences
  script:
    - git ls-remote "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/3mdeb/universal-devices/coreboot.git" | grep ${CI_COMMIT_REF_NAME}
  only:
    - web

build_heads:
  variables:
    GIT_STRATEGY: none
  image: 3mdeb/heads-docker
  stage: build_heads
  tags:
    - docker
  script:
    - git clone "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/3mdeb/universal-devices/heads.git" -b universal_devices /home/heads/heads
    - cd /home/heads/heads
    - make BOARD=apu2
    - cp -v /home/heads/heads/build/apu2/initrd.cpio.xz ${RELEASE_DIR}/initrd.cpio.xz
    - cp -v /home/heads/heads/build/apu2/bzImage ${RELEASE_DIR}/bzImage
  artifacts:
    paths:
      - ${RELEASE_DIR}/initrd.cpio.xz
      - ${RELEASE_DIR}/bzImage
  only:
    - web

build_coreboot:
  variables:
    GIT_STRATEGY: none
  image: coreboot/coreboot-sdk:1.52
  stage: build_coreboot
  tags:
    - docker
  script:
    - git clone "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/3mdeb/universal-devices/coreboot.git" -b ${CI_COMMIT_REF_NAME} /home/coreboot/coreboot
    - git clone "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/3mdeb/universal-devices/seabios.git" -b universal_devices /home/coreboot/coreboot/payloads/external/SeaBIOS/seabios
    - git clone "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/3mdeb/universal-devices/sortbootorder.git" -b universal_devices /home/coreboot/coreboot/payloads/external/sortbootorder/sortbootorder
    - cd /home/coreboot/coreboot
    - cp ${RELEASE_DIR}/initrd.cpio.xz /home/coreboot/coreboot/initrd.cpio.xz
    - cp ${RELEASE_DIR}/bzImage /home/coreboot/coreboot/bzImage
    - cp configs/config.pcengines_apu2_vboot .config
    - make olddefconfig && make
    - cp -v /home/coreboot/coreboot/build/coreboot.rom ${RELEASE_DIR}/apu2_vboot_${CI_COMMIT_REF_NAME}.rom
    - ls -al ${RELEASE_DIR}
  artifacts:
    name: ${IMAGE}
    paths:
      - ${RELEASE_DIR}/apu2_vboot_${CI_COMMIT_REF_NAME}.rom
  only:
    - web
