stages:
  - build

build:
  image: coreboot/coreboot-sdk:1.52
  stage: build
  tags:
   - local
  variables:
      GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add $GITLAB_SSH_PRIVATE_KEY
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git submodule update --init --recursive --checkout
  script:
    - ./build.sh
  artifacts:
    paths:
      - dasharo*.tar.gz
