# Dasharo project configuration data
file_version: 0.0.1

dasharo:
  platform: raptor-cs_talos-2
  newsletter:
    url: https://newsletter.3mdeb.com/subscription/w2Y2G4Rrj

client:
  name: Insurgo

framework:
  name: coreboot
  version: 5621a1e
  url_template: https://github.com/Dasharo/coreboot/tree/COMMIT_HASH

components:
- name: skiboot
  version: 04-16-2019
  url_template: https://git.raptorcs.com/git/talos-skiboot/tree/?id=COMMIT_HASH
  path: payloads/external/skiboot/talos-skiboot

documentation:
  name: Dasharo Compatibility
  url: https://docs.dasharo.com/
  building_url: https://docs.dasharo.com/variants/talos_2/building-manual/
  flashing_url: https://docs.dasharo.com/variants/talos_2/installation-manual/

platform:
  vendor: Raptor Computing Systems
  model: Talos II

tests:
  hardware_matrix: https://docs.dasharo.com/variants/talos_2/hardware-matrix/
  results: https://docs.google.com/spreadsheets/d/1KpmuPEkWOj3SieophUbgf7CF6mydliMsEDLtOFOrKn0/edit?usp=sharing
  specification: https://docs.google.com/spreadsheets/d/1KpmuPEkWOj3SieophUbgf7CF6mydliMsEDLtOFOrKn0/edit?usp=sharing

asciinema:
  signature_verification: https://asciinema.org/a/415457
