# Dasharo project configuration data

dasharo:
  platform: asus_kgpe-d16

client:
  name: Immunefi

framework:
  name: coreboot
  version: 4.14
  url_template: https://github.com/Dasharo/coreboot/commit/COMMIT_HASH
  payload: seabios

components:
    - name: SeaBIOS
      version: rel-1.14.0
      url_template: https://review.coreboot.org/plugins/gitiles/seabios/+/COMMIT_HASH
      path: payloads/external/SeaBIOS/seabios
    - name: iPXE
      version: 2019.3
      url_template: https://github.com/ipxe/ipxe/commit/COMMIT_HASH
      path: payloads/external/iPXE/ipxe
    - name: nvramcui
      version: 4.14
      url_template: https://github.com/Dasharo/coreboot/blob/COMMIT_HASH/payloads/nvramcui/nvramcui.c
      path: .

documentation:
  name: Dasharo Compatibility
  url: https://docs.dasharo.com/
  building_url: https://docs.dasharo.com/variants/asus_kgpe_d16/building-manual/
  flashing_url: https://docs.dasharo.com/variants/asus_kgpe_d16/setup/#flashing

platform:
  vendor: ASUS
  model: KGPE-D16

tests:
  specification: https://docs.google.com/spreadsheets/d/1rsJECHmYrpkPSByTyt7jmMuQnExE20zW7Zk6c8oMk6E/edit#gid=0
  hardware_matrix: https://docs.dasharo.com/variants/asus_kgpe_d16/hardware-matrix/
  results: https://docs.google.com/spreadsheets/d/1rsJECHmYrpkPSByTyt7jmMuQnExE20zW7Zk6c8oMk6E/edit#gid=0

asciinema:
  signature_verification: https://asciinema.org/a/448247
