file_version: 0.0.1

dasharo:
  platform: protectli_vault_kbl
  newsletter:
    url:  https://newsletter.3mdeb.com/subscription/n2EpSxtqL

client:
  name: Protectli

framework:
  name: coreboot
  version: 87f9fc85
  url_template: https://github.com/Dasharo/coreboot/commits/COMMIT_HASH

components:
  - name: seabios
    url_template: https://github.com/Dasharo/SeaBIOS/commits/COMMIT_HASH
    path: payloads/external/SeaBIOS/seabios
    version: v1.0.6

  - name: ipxe
    url_template: https://github.com/ipxe/ipxe/commits/COMMIT_HASH
    path: payloads/external/iPXE/ipxe
    version: 2019.3 stable

  - name: memtest
    url_template: https://review.coreboot.org/plugins/gitiles/memtest86plus/+/COMMIT_HASH
    path: payloads/external/Memtest86Plus/memtest86plus
    version: v002

documentation:
  name: Dasharo Documentation
  url: https://docs.dasharo.com/
  building_url: https://docs.dasharo.com/variants/protectli_fw6/building-manual/
  flashing_url: https://docs.dasharo.com/variants/protectli_fw6/installation-manual/
  overview_url: https://docs.dasharo.com/variants/protectli_fw6/overview/

platform:
  vendor: Protectli
  model: FW6

tests:
  specification: https://docs.dasharo.com/unified-test-documentation/overview/
  hardware_matrix: http://docs.dasharo.com/variants/protectli_fw6/hardware-matrix/
  results: https://docs.google.com/spreadsheets/d/1wI0qBSLdaluayYsm_lIa9iJ9LnPnCOZ9eNOyrKSc-j4/edit#gid=1325547345

asciinema:
  signature_verification: https://asciinema.org/a/388861
