# Dasharo project configuration data
file_version: v0.0.1

dasharo:
  platform: tuxedo_ibs15
  newsletter:
    url: https://newsletter.3mdeb.com/subscription/7IPf_aUHR

client:
  name: TUXEDO

framework:
  name: coreboot
  version: 4.16
  url_template: https://github.com/Dasharo/coreboot/commit/COMMIT_HASH

components:
- name: tianocore
  version: 9522071f7497a1a0b1077d2b0d5fcc97a126cfd0
  url_template: https://github.com/Dasharo/edk2/commit/COMMIT_HASH
  path: payloads/external/tianocore/tianocore

documentation:
  name: Dasharo Documentation
  url: https://docs.dasharo.com/
  building_url: https://docs.dasharo.com/variants/tuxedo_ibs15/building/
  flashing_url: https://docs.dasharo.com/variants/tuxedo_ibs15/installation/

platform:
  vendor: TUXEDO
  model: IBS15 Gen6

tests:
  hardware_matrix: https://docs.dasharo.com/variants/tuxedo_ibs15/testing_configuration/
  results: https://docs.google.com/spreadsheets/d/126oG3VLk51sTIz-uVIAOTVPxA0qpH9wQ4P-ue2fJLtI/edit#gid=0
  specification: https://docs.dasharo.com/unified-test-documentation/overview/

asciinema:
  signature_verification: https://asciinema.org/a/475997
