# Dasharo project configuration data

dasharo:
  platform: raptor-cs_talos-2

client:
  name: Insurgo

framework:
  name: coreboot
  version: 5621a1e
  payload: skiboot

documentation:
  name: Dasharo Compatibility
  url: https://docs.dasharo.com/
  building_url: https://docs.dasharo.com/variants/talos_2/building-manual/
  flashing_url: https://docs.dasharo.com/variants/talos_2/installation-manual/

platform:
  vendor: Raptor Computing Systems
  model: Talos II

tests:
  hardware_matrix: https://docs.dasharo.com/variants/talos_2/hardware-matrix/
  results: https://docs.google.com/spreadsheets/d/1KpmuPEkWOj3SieophUbgf7CF6mydliMsEDLtOFOrKn0/edit?usp=sharing
  specification: https://docs.google.com/spreadsheets/d/1KpmuPEkWOj3SieophUbgf7CF6mydliMsEDLtOFOrKn0/edit?usp=sharing

asciinema:
  signature_verification: https://asciinema.org/a/415457
