# Dasharo project configuration data
file_version: 1.0.0

dasharo:
        platform: clevo_nv41mz
        newsletter:
                url:  https://newsletter.3mdeb.com/subscription/T61MyO2sP

client:
        name: NovaCustom

framework:
        name: coreboot
        version: ae9a8447
        url_template: https://github.com/Dasharo/coreboot/tree/COMMIT_HASH

components:
        - name: edk2
          version: 2020.03.17
          path: payloads/external/tianocore/tianocore
          url_template: https://github.com/Dasharo/edk2/tree/COMMIT_HASH
        - name: Blobs
          version: v1.0
          path: 3rdparty/dasharo-blobs
          url_template: https://gitlab.com/novacustom/blobs/-/tree/COMMIT_HASH

documentation:
        name: Dasharo Documentation
        url: https://docs.dasharo.com/
        building_url: https://docs.dasharo.com/variants/clevo_nv41/building/
        flashing_url: https://docs.dasharo.com/variants/clevo_nv41/flashing_internal/

platform:
        vendor: Clevo
        model: NV41MZ

tests:
        specification: https://novacustom.gitlab.io/dasharo-compatibility/dasharo-compatibility/
        hardware_matrix: https://novacustom.gitlab.io/dasharo-compatibility/hardware/clevo-nv41/testing_configuration/
        results: https://docs.google.com/spreadsheets/d/1LOXY9HCu-fMitkYwX08iLsQdSNenzyU0LnMdVbZB5Do/edit#gid=0

asciinema:
        signature_verification: https://asciinema.org/a/433461
