name: Build coreboot for the NS5X target
on:
  push:
    branches:
      - novacustom_ns5x/develop
      - novacustom_ns5x/release
      - 'novacustom_ns5x/rel_*'
    tags:
      - 'novacustom_ns5x*'
  pull_request:
    branches:
      - novacustom_ns5x/develop
      - novacustom_ns5x/release

jobs:
  build:
    runs-on: [self-hosted, builder]
    steps:
    - name: Runner information
      run: |
        date
        id -u
        id -g
        ls -la

    # go modules are read only
    # https://github.com/golang/go/issues/35615
    - name: Allow for removal of go modules
      run: |
        (test -d $GITHUB_WORKSPACE/go && chmod u+w -R $GITHUB_WORKSPACE/go) || true

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # Checkout pull request HEAD commit instead of merge commit
        # See: https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
        ref: ${{ github.event.pull_request.head.sha }}
        # Fetch complete history
        fetch-depth: 0

    - name: Add review.coreboot.org/coreboot.git as origin
      run: |
        git remote add dasharo https://github.com/dasharo/coreboot.git
        git remote set-url origin https://review.coreboot.org/coreboot.git
        git fetch origin

    - name: Repository information
      run: |
        git --version
        git rev-parse --verify HEAD
        git log -n 1
        git log --graph --decorate --pretty=oneline --abbrev-commit -n 20
        git remote -v

    - name: Checkout all submodules
      run: git submodule update --init --recursive --checkout

    - name: Build NS5X target
      run: |
        docker run -v $GITHUB_WORKSPACE:/home/coreboot:rw -i --rm \
          --workdir=/home/coreboot -u$(id -u):$(id -g) coreboot/coreboot-sdk:0ad5fbd48d << EOF
        ./build.sh build-CI
        EOF

    - name: Build NS5X target (vboot test binaries)
      run: |
        docker run -v $GITHUB_WORKSPACE:/home/coreboot:rw -i --rm \
          --workdir=/home/coreboot -u$(id -u):$(id -g) coreboot/coreboot-sdk:0ad5fbd48d << EOF
        ./build.sh build-CI -s
        EOF

    - name: Save NS5X artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "dasharo-novacustom-ns5x"
        path: |
          artifacts/
        retention-days: 7
