name: NovaCustom TGL/ADL
on:
  push:
    branches:
      - novacustom_*/rel_*
  pull_request:
    branches:
      - dasharo/release

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: coreboot/coreboot-sdk:2021-09-23_b0d87f753c
      options: --user 1001
    strategy:
      matrix:
        vendor: [ novacustom ]
        model: [ nv4x_adl, ns5x_adl, nv4x_tgl, ns5x_adl ]
        build: [ debug, release ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Checkout pull request HEAD commit instead of merge commit
          # See: https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}
          # Fetch complete history
          fetch-depth: 0
      - name: Checkout all submodules
        run: git submodule update --init --recursive --checkout
      - name: Build Dasharo
        run: |
          make distclean
          make ./util/kconfig/merge_config.sh configs/config.${{ matrix.vendor }}_${{ matrix.model }} configs/fragments/config.${{ matrix.vendor }}_${{ matrix.build }}_build
          make
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "dasharo-${{ matrix.vendor }}-${{ matrix.model }}"
          path: |
            build/coreboot.rom
          retention-days: 30
