name: NovaCustom TGL/ADL
on:
  push:
    branches:
      - clevo/develop
      - clevo/release
  pull_request:
    branches:
      - clevo/develop
      - clevo/release

jobs:
  build_tgl:
    runs-on: ubuntu-22.04
    container:
      image: coreboot/coreboot-sdk:0ad5fbd48d
      options: --user 1001
    strategy:
      matrix:
        include:
          - vendor: novacustom
            model: nv4x_tgl
          - vendor: novacustom
            model: ns5x_tgl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Checkout pull request HEAD commit instead of merge commit
          # See: https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}
          # Fetch complete history
          fetch-depth: 0
      - name: Checkout all submodules
        run: git submodule update --init --recursive --checkout
      - name: Build Dasharo
        run: |
          make distclean
          cp configs/config.${{ matrix.vendor }}_${{ matrix.model }} .config
          make olddefconfig
          make
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "dasharo-${{ matrix.vendor }}-${{ matrix.model }}"
          path: |
            build/coreboot.rom
          retention-days: 30

  build_adl:
    runs-on: ubuntu-22.04
    container:
      image: coreboot/coreboot-sdk:2021-09-23_b0d87f753c
      options: --user 1001
    strategy:
      matrix:
        include:
          - vendor: novacustom
            model: nv4x_adl
          - vendor: novacustom
            model: ns5x_adl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Checkout pull request HEAD commit instead of merge commit
          # See: https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}
          # Fetch complete history
          fetch-depth: 0
      - name: Checkout all submodules
        run: git submodule update --init --recursive --checkout
      - name: Build Dasharo
        run: |
          make distclean
          cp configs/config.${{ matrix.vendor }}_${{ matrix.model }} .config
          make olddefconfig
          make
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "dasharo-${{ matrix.vendor }}-${{ matrix.model }}"
          path: |
            build/coreboot.rom
          retention-days: 30
