name: Build coreboot for the POWER9 Talos II target
on:
  push:
    branches:
      - talos_2_support
      - squashed_talos_2_support
      - talos_2_support_ramstage
      - talos_2_support_payload
  pull_request:
    branches:
      - talos_2_support
      - squashed_talos_2_support
      - talos_2_support_ramstage
      - talos_2_support_payload
    tags:
      - 'dasharo-trustworthy-computing-*'

jobs:
  build:
    runs-on: [self-hosted, builder]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # Checkout pull request HEAD commit instead of merge commit
        # See: https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
        ref: ${{ github.event.pull_request.head.sha }}
        # Fetch complete history
        fetch-depth: 0
    - name: Checkout all submodules
      run: git submodule update --init --recursive --checkout

    - name: Build information
      run: |
        date
        id -u
        git --version
        git rev-parse --verify HEAD
        git log -n 1
        git log --graph --decorate --pretty=oneline --abbrev-commit -n 20

    # Run build for just one random x86 mainboard so we can finish the build on
    # public runnner. Building all of them takes 4+ hours and we run out of
    # space. This already should give us some idea if we break something in
    # common code.
    - name: Run upstream coreboot tests (for one mainboard)
      run: |
        docker run -v $GITHUB_WORKSPACE:/home/coreboot:rw -i --rm \
          --workdir=/home/coreboot -u$(id -u):$(id -g) 3mdeb/coreboot-sdk:mkimage << EOF
        make -j $(nproc) what-jenkins-does JENKINS_ABUILD_OPT="-t intel/glkrvp"
        EOF

    - name: Build Talos II target (bootblock in PNOR)
      run: |
        docker run -v $GITHUB_WORKSPACE:/home/coreboot:rw -i --rm \
          --workdir=/home/coreboot -u$(id -u):$(id -g) 3mdeb/coreboot-sdk:mkimage << EOF
        cp configs/config.raptor-cs-talos-2 .config
        make olddefconfig
        make -j $(nproc)
        EOF

    - name: Save Talos II artifacts
      uses: actions/upload-artifact@v2
      with:
        name: coreboot-binary
        path: |
          build/coreboot.rom
          build/coreboot.rom.signed.ecc
          build/bootblock.signed.ecc
        retention-days: 7

    - name: Build Talos II target (bootblock in SEEPROM)
      run: |
        docker run -v $GITHUB_WORKSPACE:/home/coreboot:rw -i --rm \
          --workdir=/home/coreboot -u$(id -u):$(id -g) 3mdeb/coreboot-sdk:mkimage << EOF
        make clean
        cp configs/config.raptor-cs-talos-2-bootblock-in-seeprom .config
        make olddefconfig
        make -j $(nproc)
        EOF

  build-freebsd:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # Checkout pull request HEAD commit instead of merge commit
        # See: https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
        ref: ${{ github.event.pull_request.head.sha }}
        # Fetch complete history
        fetch-depth: 0
    - name: Checkout all submodules
      run: git submodule update --init --recursive --checkout

    - name: Build some tools in FreeBSD VM
      id: test
      uses: vmactions/freebsd-vm@v0.1.4
      with:
        usesh: true
        mem: 2048
        prepare: |
          pkg install -y git gmake gcc pciutils openssl pkgconf bash
        run: |
          gmake -C util/amdfwtool
          gmake -C util/cbmem
          gmake -C util/futility
          gmake -C util/inteltool
          gmake -C util/intelvbttool
          gmake -C util/nvramtool
          gmake -C util/superiotool
          gmake -C util/ifdtool
          gmake -C util/cbfstool
